class User {
  String firstName;
  String lastName;
  String number;
  String email;
  String cardNumber;

  User(
      {this.firstName,
      this.lastName,
      this.number,
      this.email,
      this.cardNumber});

  User.fromJson(Map<String, dynamic> json) {
    firstName = json['firstName'];
    lastName = json['lastName'];
    number = json['number'];
    email = json['email'];
    cardNumber = json['cardNumber'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['number'] = this.number;
    data['email'] = this.email;
    data['cardNumber'] = this.cardNumber;
    return data;
  }
}

class Autogenerated {
  String fristName;
  String lastName;
  String number;
  String email;
  String cardNumber;

  Autogenerated(
      {this.fristName,
      this.lastName,
      this.number,
      this.email,
      this.cardNumber});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    fristName = json['firstName'];
    lastName = json['lastName'];
    number = json['number'];
    email = json['email'];
    cardNumber = json['cardNumber'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['firstName'] = this.fristName;
    data['lastName'] = this.lastName;
    data['number'] = this.number;
    data['email'] = this.email;
    data['cardNumber'] = this.cardNumber;
    return data;
  }
}
